import { Content, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Contexts from "./contexts/contexts";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const hamid = localFont({
  src: "../../assets/font/ArchivoBlack-Regular.ttf",
  variable: "--font-hamid",
  display: "swap",
});
const reza = localFont({
  src: "../../assets/font/SecularOne-Regular.ttf",
  variable: "--font-reza",
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "flatrate.design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hamid.variable} ${reza.variable} antialiased `}
      >
        <Contexts>
          
          {children}
          </Contexts>
      </body>
    </html>
  );
}
